export const PUBLISH_STATUSES = {
  DRAFT: 'DRAFT',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  WAITING_CAPTCHA: 'WAITING_CAPTCHA',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
} as const;

export const PUBLISH_CHECKPOINTS = {
  PREPARE: 'PREPARE',
  SESSION_READY: 'SESSION_READY',
  PAGE_READY: 'PAGE_READY',
  BASIC_INFO_FILLED: 'BASIC_INFO_FILLED',
  ATTRIBUTES_FILLED: 'ATTRIBUTES_FILLED',
  SKU_FILLED: 'SKU_FILLED',
  IMAGES_UPLOADED: 'IMAGES_UPLOADED',
  SUBMIT_READY: 'SUBMIT_READY',
  PUBLISHED: 'PUBLISHED',
} as const;

export const CAPTCHA_TEXT_PATTERNS = [
  '验证码',
  '请完成验证',
  '安全验证',
  '滑块',
  '拖动滑块',
  '二次验证',
];
